const curatedStories = [
  {id:1,type:'Perturbador',title:'Caso Ricardo López — el acosador de Björk',short:'Documentó durante meses su obsesión y el plan de enviar una bomba a la cantante en 22 horas de diarios en vídeo.',place:'EE. UU. · 1996',score:96,footage:99,virality:96,fit:92,recent:21,sources:[['Investigación de ABC News','https://abcnews.com/Primetime/story?id=132422','TV y contexto periodístico'],['Ficha del caso y videodiarios','https://en.wikipedia.org/wiki/Ricardo_L%C3%B3pez_(stalker)','Cronología y referencias']]},
  {id:2,type:'Perturbador',title:'Timothy Treadwell — el caso Grizzly Man',short:'Vivió trece veranos junto a osos de Alaska y dejó decenas de horas de grabaciones personales antes de morir atacado.',place:'Alaska · 2003',score:95,footage:98,virality:94,fit:93,recent:20,sources:[['Informe oficial del National Park Service','https://www.nps.gov/aboutus/foia/upload/03-109_KATM_Treadwell_fatality_REDACTED.pdf','Informe oficial'],['Archivo y contexto de sus grabaciones','https://www.latimes.com/archives/la-xpm-2005-jul-10-ca-grizzly10-story.html','Prensa y footage personal']]},
  {id:3,type:'Desaparición',title:'Caso Elisa Lam — Hotel Cecil',short:'La última imagen conocida de Elisa fue un vídeo de ascensor difundido por la policía durante su desaparición.',place:'Los Ángeles · 2013',score:94,footage:94,virality:98,fit:91,recent:19,sources:[['Comunicado y vídeo del LAPD','https://www.lapdonline.org/newsroom/detectives-looking-for-missing-canadian-woman-young-womans-disappearance-from-downtown-hotel-is-suspicious-nr13034rf/','CCTV · fuente policial'],['Informe forense','https://www.autopsyfiles.org/reports/Other/lam%2C%20elisa_report.pdf','Documento del caso']]},
  {id:4,type:'Supervivencia',title:'Vuelo 571 — tragedia de los Andes',short:'Dieciséis personas sobrevivieron 72 días tras el accidente del avión de la Fuerza Aérea Uruguaya en los Andes.',place:'Argentina · 1972',score:94,footage:93,virality:95,fit:94,recent:18,sources:[['Hemeroteca de 1972','https://www.theguardian.com/theguardian/1972/dec/23/fromthearchive','Prensa contemporánea'],['Fotografías del rescate','https://commons.wikimedia.org/wiki/File:Andes_Plane_Crash_Victims_Near_Wreckage,_Dec._27,_1972.jpg','Archivo fotográfico']]},
  {id:5,type:'Supervivencia',title:'Rescate de la cueva Tham Luang',short:'Doce jóvenes futbolistas y su entrenador quedaron aislados durante 18 días en una cueva inundada de Tailandia.',place:'Tailandia · 2018',score:93,footage:97,virality:93,fit:92,recent:17,sources:[['Vídeo liberado por los Navy SEALs tailandeses','https://www.youtube.com/watch?v=F1ae81i0ZZM','Vídeo del rescate · NBC News'],['Informe del British Cave Rescue Council','https://www.caverescue.org.uk/wp-content/uploads/2018/07/BCRC-Media-Briefing-Report-11_Thai-cave-rescue-incident_080718_Short.pdf','Documento técnico']]},
  {id:6,type:'Supervivencia',title:'Juliane Koepcke — única superviviente del vuelo 508',short:'Con 17 años sobrevivió a la caída del avión y caminó durante días por la selva amazónica hasta encontrar ayuda.',place:'Perú · 1971',score:91,footage:83,virality:95,fit:96,recent:16,sources:[['Entrevista y reconstrucción de CNN','https://transcripts.cnn.com/show/cnr/date/2009-07-02/segment/05','Entrevista televisiva'],['Perfil y referencias del caso','https://en.wikipedia.org/wiki/Juliane_Koepcke','Fotos, películas y bibliografía']]},
  {id:7,type:'Supervivencia',title:'Apollo 13 — “Houston, hemos tenido un problema”',short:'Una explosión dejó a tres astronautas a 320.000 kilómetros de la Tierra con el oxígeno agotándose.',place:'Espacio · 1970',score:91,footage:99,virality:88,fit:91,recent:15,sources:[['Archivo histórico de Apollo 13','https://www.nasa.gov/wp-content/uploads/static/history/apollo_13.html','NASA · vídeo, audio y fotos'],['Documental histórico de NASA+','https://plus.nasa.gov/video/apollo-13-houston-we-ve-got-a-problem/','Footage oficial en HD']]},
  {id:8,type:'Supervivencia',title:'Los 33 mineros de la mina San José',short:'Treinta y tres mineros pasaron 69 días bajo el desierto de Atacama antes de un rescate visto en todo el mundo.',place:'Chile · 2010',score:90,footage:98,virality:90,fit:90,recent:14,sources:[['Vídeo oficial del rescate','https://www.youtube.com/watch?v=5kejd1Y6bpc','Gobierno de Chile'],['Historia oral del rescate','https://www.nasa.gov/history/history-publications-and-resources/oral-histories/chilean-miners-rescue/','NASA · entrevistas y contexto']]},
  {id:9,type:'Supervivencia',title:'Rescate de Jessica McClure — “Baby Jessica”',short:'Con 18 meses cayó a un pozo y su rescate de 58 horas fue retransmitido en directo por las grandes cadenas.',place:'Texas · 1987',score:89,footage:96,virality:91,fit:91,recent:13,sources:[['Archivo de noticias KXAS-TV','https://texashistory.unt.edu/ark:/67531/metadc725743/','Vídeo de televisión'],['Cronología del rescate','https://www.history.com/this-day-in-history/october-16/baby-jessica-rescued-from-a-well-as-the-world-watches','Hemeroteca']]},
  {id:10,type:'Desaparición',title:'Desaparición de Lars Mittank',short:'Fue grabado corriendo fuera del aeropuerto de Varna sin equipaje; desde entonces no se le ha vuelto a ver.',place:'Bulgaria · 2014',score:89,footage:88,virality:94,fit:92,recent:12,sources:[['Alerta oficial de búsqueda','https://www.schleswig-holstein.de/DE/landesregierung/ministerien-behoerden/POLIZEI/Fahndungen/fahndungen_vermisstePersonen/pdIZ_LarsMittank_/pdIZ_LarsMittank?focus=1','Policía de Schleswig-Holstein'],['Página mantenida por la familia','https://www.findet-lars-mittank.de/','Fotos y datos de contacto']]},
  {id:11,type:'Desaparición',title:'Desaparición de Brian Shaffer',short:'Las cámaras lo muestran entrando en un bar de Ohio, pero ninguna lo captó saliendo y nunca volvió a aparecer.',place:'Ohio · 2006',score:88,footage:84,virality:94,fit:92,recent:11,sources:[['Alerta de la Fiscalía de Ohio','https://www.ohioattorneygeneral.gov/Files/Briefing-Room/News-Releases/BCI/Volume-17-Number-02-Missing-Person-Brian-Shaffer-A.aspx','Fuente policial'],['Análisis del CCTV','https://www.aetv.com/articles/brian-shaffer-disappearance-2006','TV y cronología']]},
  {id:12,type:'Misterio',title:'Secuestro de señal de Max Headroom',short:'Una figura enmascarada interrumpió dos canales de Chicago; la grabación existe, pero nadie fue identificado.',place:'Chicago · 1987',score:88,footage:96,virality:93,fit:94,recent:10,sources:[['Grabación restaurada de la intrusión','https://commons.wikimedia.org/wiki/File:Max_Headroom_WTTW_Signal_Intrusion_(1987;_High_Quality_Restoration).webm','Vídeo de archivo'],['Crónica contemporánea','https://www.upi.com/Archives/1987/11/24/Video-pirate-breaks-into-regular-programing/4083564728400/','Hemeroteca']]},
  {id:13,type:'Misterio',title:'Interrupción de Southern Television — mensaje “Vrillon”',short:'Una voz que afirmaba ser extraterrestre sustituyó durante seis minutos el audio de una emisión británica.',place:'Reino Unido · 1977',score:86,footage:81,virality:91,fit:95,recent:9,sources:[['Ficha y referencias de la emisión','https://en.wikipedia.org/wiki/Southern_Television_broadcast_interruption','Audio y hemeroteca'],['Archivo de intrusiones televisivas','https://en.wikipedia.org/wiki/Broadcast_signal_intrusion','Contexto técnico']]},
  {id:14,type:'Misterio',title:'Vuelo MH370 de Malaysia Airlines',short:'Un Boeing 777 con 239 personas desapareció del radar; años de búsquedas solo recuperaron fragmentos.',place:'Océano Índico · 2014',score:86,footage:92,virality:91,fit:85,recent:8,sources:[['Informe oficial de investigación','https://www.mot.gov.my/en/aviation/reports/archived-report/mh370/mh370ir','Gobierno de Malasia'],['Resumen actualizado de la búsqueda','https://apnews.com/article/92faaa6a15379e67cdceced91c329a2c','AP · archivo audiovisual']]},
  {id:15,type:'Desaparición',title:'Desaparición de Amelia Earhart',short:'La aviadora desapareció sobre el Pacífico durante su vuelta al mundo; existen filmaciones de sus últimas salidas.',place:'Pacífico · 1937',score:84,footage:81,virality:89,fit:89,recent:7,sources:[['Últimos momentos filmados en tierra','https://www.si.edu/object/yt_7unHEeJkKww','Smithsonian · vídeo'],['Último despegue conocido','https://www.smithsonianmag.com/videos/a-final-takeoff/','Archivo Smithsonian']]},
  {id:16,type:'Perturbador',title:'Incidente del “Balloon Boy” — Falcon Heene',short:'Millones siguieron en directo un globo creyendo que llevaba a un niño, que apareció escondido en casa.',place:'Colorado · 2009',score:83,footage:97,virality:90,fit:92,recent:6,sources:[['Cobertura contemporánea','https://www.cbsnews.com/news/cops-convinced-balloon-boy-was-no-hoax/','TV y declaraciones'],['Revisión del caso','https://time.com/7302213/trainwreck-balloon-boy-netflix/','Entrevistas y archivo']]},
  {id:17,type:'Perturbador',title:'Erupción del monte Santa Helena',short:'La explosión lateral del volcán en 1980 fue captada por científicos, fotógrafos y cámaras desde tierra y aire.',place:'Washington · 1980',score:83,footage:99,virality:85,fit:88,recent:5,sources:[['Vídeo original de la erupción','https://www.usgs.gov/media/videos/mount-st-helens-eruption-may-18-1980','USGS · dominio público'],['Colección histórica 1980–1982','https://www.usgs.gov/data/historical-video-footage-mount-st-helens-volcano-washington-1980-1982','USGS · archivo descargable']]},
  {id:18,type:'Perturbador',title:'Erupción de Whakaari / White Island',short:'Turistas y cámaras de vigilancia registraron los minutos anteriores y la erupción volcánica de 2019.',place:'Nueva Zelanda · 2019',score:82,footage:94,virality:88,fit:88,recent:4,sources:[['Vídeo presentado durante el juicio','https://www.itv.com/news/2023-07-12/whakaari-new-footage-shows-moment-white-island-volcano-erupted','Footage de la erupción'],['Registro audiovisual de Nueva Zelanda','https://digitalnz.org/records/45315191','Archivo nacional']]},
  {id:19,type:'Perturbador',title:'Tragedia de Armero — caso Omayra Sánchez',short:'La erupción del Nevado del Ruiz destruyó Armero y la agonía de Omayra fue registrada por prensa internacional.',place:'Colombia · 1985',score:81,footage:91,virality:88,fit:86,recent:3,sources:[['Testimonio del cámara Evaristo Canete','https://www.rtve.es/play/videos/el-ojo-en-la-noticia/ojo-noticia-evaristo-canete-imagen-omaira/1305894/','RTVE · archivo televisivo'],['Ficha y referencias del caso','https://es.wikipedia.org/wiki/Omayra_S%C3%A1nchez','Fotos y hemeroteca']]},
  {id:20,type:'Crimen',title:'Caso D. B. Cooper — secuestro del vuelo 305',short:'Un hombre secuestró un avión, cobró un rescate y saltó en paracaídas; su identidad nunca fue confirmada.',place:'EE. UU. · 1971',score:80,footage:78,virality:91,fit:94,recent:2,sources:[['Expediente del caso','https://www.archives.gov/seattle/highlights/d-b-cooper','National Archives'],['Archivo histórico del FBI','https://archives.fbi.gov/archives/news/stories/2007/december/dbcooper_123107','FBI · fotos y documentos']]},
  {id:21,type:'Crimen',title:'Caso de los hermanos Menéndez',short:'Lyle y Erik Menéndez admitieron haber matado a sus padres; su primer juicio fue televisado casi íntegramente.',place:'California · 1989–1994',score:79,footage:99,virality:87,fit:78,recent:1,sources:[['Juicio completo de 1993','https://www.courttv.com/trials/ca-v-menendez-1993/','Court TV · archivo judicial'],['Cintas de confesión del juicio','https://www.youtube.com/watch?v=lpjDts3p7Vc','Court TV · vídeo']]}
];
const stories = [...(window.HORRORTALES_EDITORIAL || []), ...(window.HORRORTALES_WEEKLY || []), ...curatedStories];
let saved = JSON.parse(localStorage.getItem('horrortales-saved')||'[]');
let current = stories;
const $=s=>document.querySelector(s); const esc=s=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function render(){const type=$('#typeFilter').value, min=Number($('#footageFilter').value), q=$('#searchInput').value.toLowerCase(); current=stories.filter(s=>(type==='all'||s.type===type)&&s.footage>=min&&(!q||`${s.title} ${s.short} ${s.place} ${s.type}`.toLowerCase().includes(q))); const sort=$('#sortFilter').value; current.sort((a,b)=>sort==='footage'?b.footage-a.footage:sort==='recent'?(b.recent||0)-(a.recent||0):b.score-a.score); $('#storyGrid').innerHTML=current.map(card).join(''); $('#emptyState').classList.toggle('hidden',current.length>0); const weekly=current.filter(s=>s.weekly).length; $('#resultsMeta').textContent=`${current.length} historias · ${weekly} nuevas esta semana · fuentes enlazadas`; $('#savedCount').textContent=saved.length;}
function card(s){return `<article class="story-card ${s.weekly?'weekly-story':''}" data-id="${s.id}"><div class="story-thumb thumb-${s.id}"><div class="thumb-noise"></div><span class="type-pill">${s.type.toUpperCase()}</span>${s.weekly?'<span class="weekly-pill">NUEVO · TENDENCIA</span>':''}<button class="save-btn ${saved.includes(s.id)?'saved':''}" data-save="${s.id}">${saved.includes(s.id)?'★':'☆'}</button><span class="score-badge">${s.score} / 100</span></div><div class="story-body"><h3>${s.title}</h3><p>${s.short}</p><div class="story-meta"><span>${s.place}</span><strong class="good">▰ ${s.footage}% footage</strong></div></div></article>`}
function openStory(id){const s=stories.find(x=>x.id===id); const trend=s.weekly?`<p class="trend-note">Detectado el ${s.discoveredAt||'viernes'} · ${s.trendSignals||'tendencia reciente con material visual'}</p>`:''; $('#modalContent').innerHTML=`<div class="modal-layout"><div><div class="eyebrow">${s.type.toUpperCase()} · ${s.place}</div><h2>${s.title}</h2><p class="description">${s.short} El sistema ha detectado potencial narrativo, material visual y puntos de giro para un vídeo de entre 2 y 8 minutos.</p>${trend}<div class="modal-actions"><button class="primary-button" data-script="${s.id}">Preparar investigación →</button><button class="secondary-button" data-save="${s.id}">${saved.includes(s.id)?'★ Guardada':'☆ Guardar historia'}</button></div></div><div><div class="score-panel"><div class="score-head"><div><small>SCORE HORRORTALES</small><div class="big-score">${s.score}<small>/100</small></div></div><div class="eyebrow">${s.weekly?'TENDENCIA SEMANAL':'CASO CURADO'}</div></div>${[['Viralidad estimada',s.virality],['Footage potencial',s.footage],['Encaje narrativo',s.fit]].map(x=>`<div class="score-line"><label><span>${x[0]}</span><b>${x[1]}</b></label><div class="bar"><i style="width:${x[1]}%"></i></div></div>`).join('')}</div><div class="source-list"><h4>Fuentes y material detectado</h4>${s.sources.map(x=>`<div class="source"><span>↗</span><div><a href="${x[1]}" target="_blank" rel="noopener">${x[0]}</a><small>${x[2]}</small></div></div>`).join('')}</div></div></div>`; $('#storyModal').classList.remove('hidden');}
function generate(id){const s=stories.find(x=>x.id===id); const script=`HOOK · 0:00 — 0:03\n“${s.type==='Supervivencia'?'Durante 72 horas, una cámara siguió grabando bajo la montaña.':'Esta grabación dura unos segundos. Pero lo que ocurrió después sigue sin tener una explicación.'}”\n[Visual: ${s.sources[0][0]}]\n\nCONTEXTO · 0:03 — 0:25\n${s.title} empezó como una historia que casi nadie quiso contar. Ocurrió en ${s.place.split(' · ')[0]}, y desde el primer momento había un detalle que no encajaba: ${s.short.toLowerCase()}\n\nREHOOK · 0:25 — 0:30\n“Y aquí es donde la historia se vuelve realmente extraña.”\n\nDESARROLLO · 0:30 — 1:20\nLas primeras imágenes muestran una situación aparentemente normal. Pero al ordenar la cronología, aparecen tres pistas: el lugar, el momento y una decisión que cambia todo. Los testigos recuerdan ${s.type==='Crimen'?'una versión distinta de la escena.':'que algo no parecía estar bien.'} El material de archivo permite reconstruir lo ocurrido paso a paso, sin necesidad de inventar nada.\n\nREHOOK · 1:20 — 1:25\n“Lo más inquietante no es lo que se ve. Es lo que falta.”\n\nGIRO Y CIERRE · 1:25 — 2:00\nCuando aparece la última prueba, las piezas parecen encajar… aunque dejan una pregunta abierta. ${s.title} sigue siendo uno de esos casos donde el footage cuenta más que cualquier narrador. ¿Tú qué explicación le darías?`; $('#scriptContent').innerHTML=`<div class="script-header"><div><div class="script-tag">DRAFT · ${s.score}/100 SCORE</div><h2>${s.title}</h2></div><div class="script-tools"><button class="secondary-button" id="copyScript">Copiar texto</button><button class="primary-button small" id="downloadScript">Descargar .txt</button></div></div><div class="script-body" id="scriptText">${esc(script)}</div>`; $('#storyModal').classList.add('hidden'); $('#scriptModal').classList.remove('hidden'); $('#copyScript').onclick=()=>navigator.clipboard?.writeText(script).then(()=>toast('Guion copiado al portapapeles')); $('#downloadScript').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([script],{type:'text/plain'}));a.download=`horrortales-${s.id}-guion.txt`;a.click();};}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('horrortales-saved',JSON.stringify(saved));render();toast(saved.includes(id)?'Historia guardada':'Historia eliminada de guardadas');}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
function researchCase(id){const s=stories.find(x=>x.id===id);const duration=s.fit>=92?'2–4 minutos':s.sources.length>=2?'4–6 minutos':'2–3 minutos';const brief=`FICHA DE INVESTIGACIÓN\n\nCASO\n${s.title}\n\nDURACIÓN INICIAL RECOMENDADA\n${duration}. La duración definitiva se decide después de verificar la cronología.\n\nPUNTO DE PARTIDA\n${s.short}\n\nFUENTES DETECTADAS\n${s.sources.map((source,index)=>`${index+1}. ${source[0]}\n${source[1]}\n${source[2]}`).join('\n\n')}\n\nANTES DE ESCRIBIR EL GUION\n1. Confirmar nombres, fechas, lugares y orden de los acontecimientos.\n2. Separar hechos, testimonios, hipótesis y rumores.\n3. Localizar footage primario y revisar sus derechos de uso.\n4. Identificar el hook visual, los giros y un rehook cada 25–35 segundos.\n5. No presentar acusaciones o teorías como hechos.\n\nESTADO\nPendiente de investigación profunda y revisión editorial.`;$('#scriptContent').innerHTML=`<div class="script-header"><div><div class="script-tag">RESEARCH BRIEF · ${s.score}/100 SCORE</div><h2>${s.title}</h2></div><div class="script-tools"><button class="secondary-button" id="copyScript">Copiar ficha</button><button class="primary-button small" id="downloadScript">Descargar .txt</button></div></div><div class="script-body" id="scriptText">${esc(brief)}</div>`;$('#storyModal').classList.add('hidden');$('#scriptModal').classList.remove('hidden');$('#copyScript').onclick=()=>navigator.clipboard?.writeText(brief).then(()=>toast('Ficha copiada al portapapeles'));$('#downloadScript').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([brief],{type:'text/plain'}));a.download=`horrortales-${s.id}-investigacion.txt`;a.click();};}
const originalOpenStory = openStory;
openStory = function(id){
  originalOpenStory(id);
  const button = document.querySelector('[data-script]');
  if (button) button.textContent = 'Crear guion con Codex →';
};

researchCase = function(id){
  const s = stories.find((story) => String(story.id) === String(id));
  const sources = s.sources.map((source, index) => `${index + 1}. ${source[0]}\n${source[1]}\n${source[2]}`).join('\n\n');
  const prompt = `Trabaja en el repositorio HorrorTales. Lee AGENTS.md y sigue skills/horrortales-editorial/SKILL.md.\n\nCASO SELECCIONADO\n${s.title}\n${s.place}\n\nRESUMEN PARA EMPEZAR\n${s.short}\n\nFUENTES DETECTADAS\n${sources}\n\nTAREA\nInvestiga automáticamente este caso a fondo, sin pedirme aprobar una ficha intermedia. Confirma nombres, fechas, cronología y afirmaciones centrales con al menos dos fuentes independientes; separa hechos, testimonios, teorías y rumores; localiza y verifica vídeos, fotografías, CCTV, televisión, grabaciones o archivos disponibles. Guarda el expediente en casos/investigados/. Después crea y guarda un guion de entre 2 y 8 minutos, eligiendo la duración según la historia, con hook factual y visual en los primeros 3 segundos, narrativa cronológica, rehooks concretos cada 25–40 segundos y cierre fuerte. Incluye indicaciones de footage y notas de fact-check. No inventes datos ni enlaces.`;
  $('#scriptContent').innerHTML = `<div class="script-header"><div><div class="script-tag">CODEX · SIN API</div><h2>${s.title}</h2></div><div class="script-tools"><button class="primary-button small" id="copyScript">Copiar petición</button><button class="secondary-button" id="downloadScript">Descargar .txt</button></div></div><p class="description">Copia esta petición, vuelve al chat de Codex que tiene abierto el repositorio y pégala. Codex investigará y escribirá el guion en un único paso.</p><div class="script-body" id="scriptText">${esc(prompt)}</div>`;
  $('#storyModal').classList.add('hidden');
  $('#scriptModal').classList.remove('hidden');
  $('#copyScript').onclick = () => copyForCodex(prompt);
  $('#downloadScript').onclick = () => {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([prompt], {type: 'text/plain'}));
    a.download = `horrortales-${s.id}-peticion-codex.txt`;
    a.click();
  };
};

async function copyForCodex(text){
  try {
    if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(text);
    else {
      const area = document.createElement('textarea');
      area.value = text;
      area.style.position = 'fixed';
      area.style.opacity = '0';
      document.body.appendChild(area);
      area.select();
      document.execCommand('copy');
      area.remove();
    }
    toast('Petición copiada. Pégala en Codex.');
  } catch {
    toast('Selecciona el texto y cópialo manualmente.');
  }
}

document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){e.stopPropagation();const rawId=save.dataset.save;const id=/^\d+$/.test(rawId)?Number(rawId):rawId;toggleSave(id);if($('#storyModal').classList.contains('hidden')===false)openStory(id);return}const script=e.target.closest('[data-script]');if(script){const rawId=script.dataset.script;researchCase(/^\d+$/.test(rawId)?Number(rawId):rawId);return}const cardEl=e.target.closest('.story-card');if(cardEl){const rawId=cardEl.dataset.id;openStory(/^\d+$/.test(rawId)?Number(rawId):rawId)}if(e.target.matches('[data-close]')||e.target.classList.contains('modal-backdrop')){e.target.closest('.modal-backdrop').classList.add('hidden')}});
['searchInput','typeFilter','footageFilter','sortFilter'].forEach(id=>$('#'+id).addEventListener('input',render)); $('#searchButton').onclick=render; $('#resetFilters').onclick=()=>{$('#searchInput').value='';$('#typeFilter').value='all';$('#footageFilter').value='0';$('#sortFilter').value='score';render()}; $('#newSearch').onclick=()=>{$('#searchInput').focus();toast('Escribe un tema para iniciar la búsqueda')}; render();
